### ISSUE TITLE
Document versions of Python supported

### ISSUE THREAD

**Issue by peterjc** [sanger-pathogens/gff3toembl#42]
After spending some time on this, I have concluded that the tool currently only works or at least is only tested under Python 2.7.

There are incompatibilities under Python 2.6, e.g. using ``"blah {} {}".format(...)`` without numbering the insertion points, or use of "new" unittest methods like ``.assertIsInstance``. This looks fixable with moderate effort, but probably not worthwhile? Instead make it clear if Python 2.6 is not supported.

There are incompatibilities under Python 3, such as clear syntax errors e.g. #39. This does seem worth fixing, #40.

**Comment by peterjc** [comment]
Also I'd suggest making ``setup.py`` explicitly check and error on unsupported versions of Python.

**Comment by bewt85** [comment]
Evening @peterjc, thanks for your comments.  Your suspicions are correct and that this has only been developed on and tested with Python 2.7.  I think you're right that this could be made a lot clearer to save others from similar frustration.

While I'm slowly getting on board the Python3 train I'm not hugely excited about spending time making the changes necessary to make this Python2 and Python3 compatible.  I'll have a chat with the others in the office after the weekend but I'd not hold your breath unless it turns out that theres lots of hidden demand for this.

Having said that, I've also never converted something from Python2 to Python3 so this might be a doddle?  Maybe you're familiar with some good tools or resources?

**Comment by bewt85** [comment]
Partially addressed by #44

**Comment by peterjc** [comment]
I've got first hand experience of a a single code base running under Python 2.6, 2.7 and 3.3 or later (Biopython), while NumPy is another large example doing this. i.e. Same code which works on both without changes!

As long as your dependencies are available, this shouldn't be that bad - and TravisCI is a big help with keeping things working even if the developers mainly use just one platform.

In your case I would suggest 2.7 plus 3.4 onwards, or maybe even just 2.7 and 3.5 onwards.

I've hit enough minor glitches with Python 3.0 to 3.3 to suggest you skip them entirely.

**Comment by andrewjpage** [comment]
Now documented in the Read me that it is python 2.7 only
